export const skills = [
    "Semantic HTML",
    "CSS (Flexbox, Grid, BEM)",
    "Responsive Web Design",
    "Figma & UX/UI Design",
    "TailwindCSS",
    "Shadcn/ui & DaisyUI",
    "JavaScript (ES6+)",
    "Immutability & Error handling",
    "React (Hooks, Context, Router)",
    "Redux (Toolkit, Saga)",
    "TypeScript",
    "Working with API (fetch, axios)",
    "Promises, Async/await",
    "NPM & Git",
    "GitHub Pull Requests & Review",
    "WordPress & WooCommerce",
    "Node.js",
    "MongoDB & Mongoose",
    "PostgreSQL & MySQL",
    "Python",
    "Django & Django Rest Framework",
    "FastAPI",
    "Data Science (R, Pandas)",
    "Algorithmic Trading Strategies",
    "Docker",
    "DevOps Best Practices",
    "Scrum & Trello",
    "Teamwork & Debugging",
    "Linux",
    "Machine Learning (Scikit-learn, Keras)",
];

export const nextSkills = [
    "Machine Learning with Transformers in AlgoTrading",
    "Express.js & Nest.js",
    "Microservices Architecture",
    "Advanced Testing Skills (Unit/Integration/E2E)",
    "Full Production Ready CI/CD Pipelines",
    "Kubernetes",
    "Terraform",
    "GCP Cloud Engineer",
    "AWS Certified Solutions Architect",
];